version: "3.8"
services:
    broker-1:
        build: ./broker
        environment:
            - BROKER_ID=BROKER_1
            - PUERTO_REP=3041
            - PUERTO_PUB=3031
            - PUERTO_SUB=3021
        ports:
            - '3041:3041'
            - '3031:3031'
            - '3021:3021'
        depends_on:
            - coordinador
            - servidor-ntp
    broker-2:
        build: ./broker
        environment:
            - BROKER_ID=BROKER_2
            - PUERTO_REP=3042
            - PUERTO_PUB=3032
            - PUERTO_SUB=3022
        ports:
            - '3042:3042'
            - '3032:3032'
            - '3022:3022'
        depends_on:
            - coordinador
            - servidor-ntp
    broker-3:
        build: ./broker
        environment:
            - BROKER_ID=BROKER_3
            - PUERTO_REP=3043
            - PUERTO_PUB=3033
            - PUERTO_SUB=3023
        ports:
            - '3043:3043'
            - '3033:3033'
            - '3023:3023'
        depends_on:
            - coordinador
            - servidor-ntp
    coordinador:
        build: ./coordinador
        ports:
            - '3000:3000'
        depends_on:
            - servidor-ntp
    servidor-http:
        build: ./servidor-http
        ports:
            - '5000:5000'
        depends_on:
            - broker-1
            - broker-2
            - broker-3
    servidor-ntp:
        build: ./servidor-ntp
        environment:
            - PUERTO_NTP=2000
        ports:
            - '2000:2000'